authors = ["Martin Sj√∂lund <martin.sjolund@liu.se>"]
name = "MetaModelica"
uuid = "9d7f2a79-07b5-5542-8b19-c0100dda6b06"
version = "0.0.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
